### ISSUE TITLE
Content-Type gets overwritten to text/plain with attachment

### ISSUE THREAD

**Issue by captn3m0** [awdeorio/mailmerge#100]
Template:

```
From: a@example.invalic
TO: b@example.invalic
SUBJECT: Hello
ATTACHMENT: a.txt
CONTENT-TYPE: text/html

<html>
<body>
<p>Hi,</p>
</body>
</html>

```

command: `mailmerge --database database.csv --template 04.tpl  --output-format raw`

output:

```
>>> message 1
Content-Type: multipart/alternative;
 boundary="===============1872202902524908882=="
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
SUBJECT: Hello
From: a@example.invalic
TO: b@example.invalic
Date: Wed, 05 Aug 2020 21:37:21 -0000

--===============1872202902524908882==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<html>
<body>
<p>Hi,</p>
</body>
</html>
--===============1872202902524908882==
Content-Type: application/octet-stream; Name="a.txt"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="a.txt"

aGVsbG93b3JsZA==

--===============1872202902524908882==--
>>> message 1 sent
>>> Limit was 1 message.  To remove the limit, use the --no-limit option.
>>> This was a dry run.  To send messages, use the --no-dry-run option.
```

The important part being `Content-Type: text/plain; charset="us-ascii"`, which is incorrect. Using a [html+plaintext](https://github.com/awdeorio/mailmerge#html-and-plain-text) message works, but that is more complicated.

**Comment by captn3m0** [comment]
Tested this against the latest `develop`.

**Comment by awdeorio** [comment]
Thanks for the cogent bug report @captn3m0 !  @seshrs any insights?

**Comment by seshrs** [comment]
Good catch! I suspect the issue is here:

https://github.com/awdeorio/mailmerge/blob/d08667a8f2a7a9e7ad64e58c2bc049a80726bf3c/mailmerge/template_message.py#L116-L122

When we create the `MIMEText` object, we preserve the original encoding by providing the `_charset` argument, but we do not preserve the MIME `_subtype`, which defaults to `plain`.

I can look into it this weekend. (Unless you want to take this on, @captn3m0? No obligation though 😃 )
