### ISSUE TITLE
Support CSV files with semicolons as separators

### ISSUE THREAD

**Issue by abtsousa** [awdeorio/mailmerge#146]
This project is amazing. However, due to my regional settings, CSV files are saved as semicolons instead of commas (which are used for decimals).

Is there a way you could add support to these? I'm tired of having to use find-replace for the script to work.

**Comment by seshrs** [comment]
Hi, thanks for the suggestion! Python makes this really easy to implement, we _could_ just accept a delimiter string as a CLI option and add a [`delimiter`](https://docs.python.org/3/library/csv.html#csv.Dialect.delimiter) variable here:
https://github.com/awdeorio/mailmerge/blob/76b5d55a59563863fe5517d34d065c07de5b2b88/mailmerge/__main__.py#L270-L273

Even better, we could use the [`Sniffer`](https://docs.python.org/3/library/csv.html#csv.Sniffer) class to automatically attempt to detect the right settings for reading the CSV file. I think this is the cleaner solution since we would not need to add a new CLI option. 

Would you like to try opening a PR with this changes? Let us know here if you need support getting started :)

**Comment by abtsousa** [comment]
Thanks for your help, I was actually looking into that as you commented. Would [this](https://github.com/awdeorio/mailmerge/issues/146) work? I'm a novice Python programmer so I apologize if my syntax is not correct, but it seems to be working right on my end.

**Comment by awdeorio** [comment]
I really like the Sniffer idea!  I'll take a look at your PR soon.
